// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbqxqpfajyevyqehkuwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxicXhxcGZhanlldnlxZWhrdXdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2Mjg3OTYsImV4cCI6MjA2MjIwNDc5Nn0.0MGJ7RuKupS_nnBSmXUH26QMIcQB8wuxstPCy_obnTc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);